###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "111",
  "email": "999",
  "password": "123456",
  "country": "India",
  "rank":"Bronze",
  "avatarUrl": "https://gravatar.com/avatar/6b6b69da5c88718d32bc60e754f59ed9?s=400&d=robohash&r=x"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "999",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/removeUser
Content-Type: application/json

{
    "email": "laksh@example.com"
}

###
GET http://localhost:5000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTYyMiwiZXhwIjoxNzYyNDE2NDIyfQ.hCF_8GChMe0S9iLM9uFqg2WAwhkvuEg18vLMMHUVtas

###
GET http://localhost:5000/api/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTYyMiwiZXhwIjoxNzYyNDE2NDIyfQ.hCF_8GChMe0S9iLM9uFqg2WAwhkvuEg18vLMMHUVtas

###
PUT http://localhost:5000/api/user/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTM2MCwiZXhwIjoxNzYyNDE2MTYwfQ.ScW7kKr5CYaZM2fORUJ5e5-Lqb6VYyqoamj51BHDLVY
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"111111"
}

###
PUT http://localhost:5000/api/user/updateProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTM2MCwiZXhwIjoxNzYyNDE2MTYwfQ.ScW7kKr5CYaZM2fORUJ5e5-Lqb6VYyqoamj51BHDLVY
Content-Type: application/json

{
  "username":"Aman Kumar",
  "email":"Aman@example.com"
}


# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTUyNCwiZXhwIjoxNzYxODEyNDI0fQ.yScDxS5dcKCDkPrsYKttazsbsxjYV5WaEqJ7mZFj1kU



### 
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json

# "token": "<refreshToken>"
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTYyMiwiZXhwIjoxNzYyNDE2NDIyfQ.hCF_8GChMe0S9iLM9uFqg2WAwhkvuEg18vLMMHUVtas"
}


###
POST http://localhost:5000/api/auth/logout
# Authorization: Bearer <accessToken>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJMdWNreUBleGFtcGxlLmNvbSIsImlhdCI6MTc2MTgxMTYyMiwiZXhwIjoxNzYyNDE2NDIyfQ.hCF_8GChMe0S9iLM9uFqg2WAwhkvuEg18vLMMHUVtas

### GET Profile
GET http://localhost:5000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoiMjIyIiwiaWF0IjoxNzYxODUxMTcwLCJleHAiOjE3NjE4NTIwNzB9.k7SYSUfiKCvif6Z_sYGSs45t73BF633kvj-dUKx34oE
### UPDATE Profile
PUT http://localhost:5000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoiMjIyIiwiaWF0IjoxNzYxODUxMTcwLCJleHAiOjE3NjE4NTIwNzB9.k7SYSUfiKCvif6Z_sYGSs45t73BF633kvj-dUKx34oE

{
  "username": "LakshRJ",
  "country": "India",
  "preferred_game_mode": "duo",
  "avatar_url": "https://gravatar.com/avatar/b826fa51825f3a0b908748970004d239?s=400&d=robohash&r=x"
}
