###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Aman",
  "email": "Aman@example.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "Aman@example.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/removeUser
Content-Type: application/json

{
    "email": "laksh@example.com"
}

###
GET http://localhost:5000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbWFuQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxODAyOTA3LCJleHAiOjE3NjI0MDc3MDd9.-m_6y1TVZbg-KQc5a4QSjYDc3hSogaHh2JW_zKZHJTI

###
GET http://localhost:5000/api/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbWFuQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxODAyOTA3LCJleHAiOjE3NjI0MDc3MDd9.-m_6y1TVZbg-KQc5a4QSjYDc3hSogaHh2JW_zKZHJTI

###
PUT http://localhost:5000/api/user/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbWFuQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxODAyOTA3LCJleHAiOjE3NjI0MDc3MDd9.-m_6y1TVZbg-KQc5a4QSjYDc3hSogaHh2JW_zKZHJTI
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"111111"
}

###
PUT http://localhost:5000/api/user/updateProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJBbWFuQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYxODAyOTA3LCJleHAiOjE3NjI0MDc3MDd9.-m_6y1TVZbg-KQc5a4QSjYDc3hSogaHh2JW_zKZHJTI
Content-Type: application/json

{
  "username":"Aman Kumar",
  "email":"Aman@example.com"
}