name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ------------------ Backend CI ------------------
  backend:
    name: Backend CI (Node.js)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: game-matchmaking-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: game-matchmaking-backend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint --if-present

      - name: Run Tests
        run: npm test --if-present

      - name: Build App
        run: npm run build --if-present

  # ------------------ Frontend CI ------------------
  frontend:
    name: Frontend CI (Flutter)
    runs-on: ubuntu-latest
    needs: backend  

    defaults:
      run:
        working-directory: game_matchmaking_frontend/game

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: stable

      - name: Get Dependencies
        run: flutter pub get
      - name: Create .env file
        run: |
          echo "PUBLIC_IP=${{ secrets.PUBLIC_IP }}" >> .env
          # Add more lines for each secret you need

      - name: Build APK
        run: flutter build apk

  deploy:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd GAME_Full-stack-Project
            git pull origin main
            cd game-matchmaking-backend
            sudo docker compose down
            sudo docker compose up -d --build
