name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-actions@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEYS}}
          script: |
            cd ~/GAME_Full-stack-Project/game-matchmaking-backend
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build